
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;

import "debotInitList.sol";

contract DebotShoppingList is AdebotInitList {

    function addProduct(uint32 index) public {
        addPurchase(index);
    }

    function getDelete(uint32 index) public {
        delPurchase(index);
    }

    function showList(uint32 index) public {
        showPurchases(index);
    }
}