
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;

import "debotInitList.sol";

// This is class that describes you smart contract.
contract DebotAtMarket is AdebotInitList {

    function showList(uint32 index) public {
        showPurchases(index);
    }

    function getDelete(uint32 index) public {
        delPurchase(index);
    }

}
